CREATE ROLE super WITH LOGIN PASSWORD 'super';

CREATE ROLE otherbrands WITH LOGIN PASSWORD 'otherbrands' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE otherbrands_database;
GRANT ALL PRIVILEGES ON DATABASE otherbrands_database TO otherbrands ;
GRANT ALL PRIVILEGES ON DATABASE otherbrands_database TO super;

CREATE ROLE bmwbrands WITH LOGIN PASSWORD 'bmwbrands' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE bmwbrands_database;
GRANT ALL PRIVILEGES ON DATABASE bmwbrands_database TO bmwbrands;
GRANT ALL PRIVILEGES ON DATABASE bmwbrands_database TO super;

CREATE ROLE carrace WITH LOGIN PASSWORD 'carrace' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE carrace_database;
GRANT ALL PRIVILEGES ON DATABASE carrace_database TO carrace;
GRANT ALL PRIVILEGES ON DATABASE carrace_database TO super;

